export interface CurrencyConfig {
  code: string;
  symbol: string;
  name: string;
  position: 'prefix' | 'suffix';
  decimals: number;
  decimalSeparator: string;
  thousandsSeparator: string;
}

export const DEFAULT_CURRENCY: CurrencyConfig = {
  code: 'IDR',
  symbol: 'Rp',
  name: 'Indonesian Rupiah',
  position: 'prefix',
  decimals: 0,
  decimalSeparator: ',',
  thousandsSeparator: '.',
};

export const CURRENCY_PRESETS: CurrencyConfig[] = [
  {
    code: 'IDR',
    symbol: 'Rp',
    name: 'Indonesian Rupiah (IDR)',
    position: 'prefix',
    decimals: 0,
    decimalSeparator: ',',
    thousandsSeparator: '.',
  },
  {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar (USD)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'EUR',
    symbol: '€',
    name: 'Euro (EUR)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: ',',
    thousandsSeparator: '.',
  },
  {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound (GBP)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar (SGD)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'MYR',
    symbol: 'RM',
    name: 'Malaysian Ringgit (MYR)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen (JPY)',
    position: 'prefix',
    decimals: 0,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar (AUD)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'CAD',
    symbol: 'C$',
    name: 'Canadian Dollar (CAD)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'PHP',
    symbol: '₱',
    name: 'Philippine Peso (PHP)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'THB',
    symbol: '฿',
    name: 'Thai Baht (THB)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'VND',
    symbol: '₫',
    name: 'Vietnamese Dong (VND)',
    position: 'suffix',
    decimals: 0,
    decimalSeparator: ',',
    thousandsSeparator: '.',
  },
  {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee (INR)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'CNY',
    symbol: '¥',
    name: 'Chinese Yuan (CNY)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'KRW',
    symbol: '₩',
    name: 'South Korean Won (KRW)',
    position: 'prefix',
    decimals: 0,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'AED',
    symbol: 'AED',
    name: 'UAE Dirham (AED)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
  {
    code: 'SAR',
    symbol: 'SAR',
    name: 'Saudi Riyal (SAR)',
    position: 'prefix',
    decimals: 2,
    decimalSeparator: '.',
    thousandsSeparator: ',',
  },
];
